### ISSUE TITLE
Node block comments not folding

### ISSUE THREAD

**Issue by kjpaul** [dakaraphi/vscode-extension-common#4]
Multi line JavaScript comments don't seem to be folding in Typescript like they do in WebStorm, PhpStorm etc:
/*
   Comment title
   Comment body
       comment continues...
*/

/* **Comment title** ...*/

(I'm on Windows 10 and have not tested on Mac)
Thanks.

**Comment by d-akara** [comment]
I assume maybe you intended to open this issue with https://github.com/dakaraphi/vscode-extension-fold

Nonetheless, I am not able to control the folding in this area.  This is done by VSCode internal code. 
Maybe you wish to comment here:

https://github.com/Microsoft/vscode/issues/3352

**Comment by kjpaul** [comment]
This is more than likely related to the Typescript bug referenced in https://github.com/Microsoft/TypeScript/issues/22732
